# Generated by Django 3.0.4 on 2020-08-11 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('fecha_modifica', models.DateField(auto_now=True, verbose_name='Fecha Modificacion')),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('usuario_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id_categoria'],
            },
        ),
    ]
